version: '3'

services:
  zk:
    image: ${PREFIX}zookeeper-swarm
    environment:
      - ZOO_SERVER_NAME=zk
      - ZOO_SERVER_COUNT=${ZOO_SERVER_COUNT}
    deploy:
      #replicas: ${ZOO_SERVER_COUNT}
      replicas: 1
      restart_policy:
        condition: on-failure

  zk-cli:
    image: ${PREFIX}zookeeper
    command: bash
    tty: true
    stdin_open: true
